# Generated by Django 6.0 on 2025-12-30 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop1', models.CharField(max_length=255, null=True)),
                ('stop2', models.CharField(blank=True, max_length=255, null=True)),
                ('stop3', models.CharField(blank=True, max_length=255, null=True)),
                ('stop4', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.login')),
            ],
        ),
    ]
