# Generated by Django 5.2.3 on 2025-12-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setroute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='test',
            field=models.CharField(default='x', max_length=10),
        ),
    ]
