# Generated by Django 5.2.3 on 2025-12-30 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setroute', '0002_busroute_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusRoute',
        ),
    ]
