# Generated by Django 5.2.3 on 2026-02-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusFee',
        ),
    ]
