# Generated by Django 5.2.3 on 2026-01-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
                ('stop1', models.CharField(max_length=255, null=True)),
                ('stop2', models.CharField(blank=True, max_length=255, null=True)),
                ('stop3', models.CharField(blank=True, max_length=255, null=True)),
                ('stop4', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
