# Generated by Django 5.2.3 on 2026-01-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_busroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='test',
        ),
    ]
