# Generated by Django 5.2.3 on 2026-01-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_busroute_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='stop1',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='stop2',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='stop3',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='stop4',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='user',
        ),
    ]
