# Generated by Django 5.2.3 on 2026-01-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_busroute_created_at_remove_busroute_stop1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='stop1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='stop2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='stop3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='stop4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
