# Generated by Django 5.2.3 on 2026-01-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentwallet'),
        ('student', '0005_busroute_created_at_busroute_stop1_busroute_stop2_and_more'),
    ]

    operations = [
    ]
