# Generated by Django 5.2.3 on 2026-01-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_merge_20260104_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
