# Generated by Django 5.2.3 on 2026-01-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_busroute_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='test',
        ),
    ]
