# Generated by Django 5.2.3 on 2026-01-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_busroute_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='stop3',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='stop4',
        ),
    ]
