# Generated by Django 5.2.3 on 2026-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_busroute_stop3_remove_busroute_stop4'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
                ('phone_no', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=200)),
                ('aadhaar_no', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': 'Student Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
