# Generated by Django 5.2.3 on 2026-01-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_infosubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosubmit',
            name='card_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infosubmit',
            name='card_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infosubmit',
            name='card_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
