# Generated by Django 5.2.3 on 2026-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_infosubmit_card_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnfccard',
            name='student',
        ),
        migrations.AddField(
            model_name='studentnfccard',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentnfccard',
            name='card_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='StudentWallet',
        ),
    ]
