# Generated by Django 5.2.3 on 2026-01-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_studentnfccard_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnfccard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
