# Generated by Django 5.2.3 on 2026-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_studentnfccard_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosubmit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='infosubmit',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='infosubmit',
            name='sphone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
