# Generated by Django 6.0 on 2026-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('tap_date', models.DateField()),
                ('tap_time', models.TimeField()),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bus_log',
                'ordering': ['-tap_date', '-tap_time'],
            },
        ),
        migrations.CreateModel(
            name='BusFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_stop', models.CharField(max_length=255, null=True)),
                ('dest_route', models.CharField(max_length=255, null=True)),
                ('busfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
