# Generated by Django 5.2.3 on 2026-02-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_stop', models.CharField(max_length=255, null=True)),
                ('dest_route', models.CharField(max_length=255, null=True)),
                ('busfee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
